#ifndef KERNEL_DRIVER_H
#define KERNEL_DRIVER_H

// IOCTL Codes
#define IOCTL_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SCAN_PATTERN CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RESOLVE_POINTER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MAP_PHYSICAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PROCESS_BASE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Structures
typedef struct _MEMORY_READ_REQUEST {
    ULONG ProcessId;
    ULONG_PTR Address;
    ULONG Size;
} MEMORY_READ_REQUEST, *PMEMORY_READ_REQUEST;

typedef struct _MEMORY_WRITE_REQUEST {
    ULONG ProcessId;
    ULONG_PTR Address;
    ULONG Size;
} MEMORY_WRITE_REQUEST, *PMEMORY_WRITE_REQUEST;

typedef struct _PATTERN_SCAN_REQUEST {
    ULONG ProcessId;
    ULONG_PTR StartAddress;
    ULONG_PTR EndAddress;
    UCHAR Pattern[256];
    UCHAR Mask[256];
    ULONG PatternSize;
    ULONG_PTR Results[1024];
    ULONG ResultCount;
} PATTERN_SCAN_REQUEST, *PPATTERN_SCAN_REQUEST;

typedef struct _POINTER_RESOLVE_REQUEST {
    ULONG ProcessId;
    ULONG_PTR BaseAddress;
    ULONG OffsetCount;
    ULONG Offsets[16];
    ULONG_PTR Result;
} POINTER_RESOLVE_REQUEST, *PPOINTER_RESOLVE_REQUEST;

typedef struct _PHYSICAL_MEMORY_MAP {
    ULONGLONG PhysicalAddress;
    ULONG Size;
    ULONG_PTR VirtualAddress;
} PHYSICAL_MEMORY_MAP, *PPHYSICAL_MEMORY_MAP;

#endif // KERNEL_DRIVER_H
